/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: inciprocal (https://sketchfab.com/inciprocal.com)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/caterpillar-work-boot-d551ce74dcd24528a05cbb0f4b7434d7
title: Caterpillar Work Boot
*/

import * as THREE from 'three'
import React, { useRef } from 'react' 
import { GLTF } from 'three-stdlib' 
import { useGLTF  } from "@react-three/drei";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    sh_catWorkBoot: THREE.MeshStandardMaterial
  }
};

interface position {
  X:number, Y:number, Z:number;
}

export default function Caterpillar({ ...props }: JSX.IntrinsicElements['group'],
              {X=-0.03,Y=0,Z=0.02}:position ) {

   
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/models/caterpillar/scene.gltf') as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null} scale={5}>
      <group position={[X, Y, Z]} rotation={[-Math.PI / 2, 0, -0.51]}>
        <mesh geometry={nodes.Object_2.geometry} 
        material={materials.sh_catWorkBoot} />
      </group>
    </group>
  );
};
 